//! Rust source generator for the runtime Kafka config catalog.

use std::collections::BTreeSet;

use proc_macro2::{Ident, TokenStream};
use quote::{format_ident, quote};

use super::model::{
    ConfigCatalogDocument, ConfigKeyDocument, ConfigOrigin, ConfigValueDefault, JavaConfigType,
    KafkaConfigClient,
};
use crate::format;

/// Native typed config keys already exposed by `kacrab`.
pub type NativeConfigKeys = BTreeSet<(KafkaConfigClient, String)>;

/// Generate `kacrab/src/config/catalog.rs` from a Kafka config snapshot.
pub fn generate_rust_catalog(
    document: &ConfigCatalogDocument,
    native_keys: &NativeConfigKeys,
) -> Result<String, format::FormatError> {
    let source_ref = document.source_ref.as_str();
    let client_catalogs: Vec<TokenStream> = document
        .clients
        .iter()
        .map(|client| client_catalog_tokens(client, native_keys))
        .collect();
    let catalog_entries: Vec<TokenStream> = document
        .clients
        .iter()
        .flat_map(|client| {
            client
                .configs
                .iter()
                .map(|config| entry_tokens(client.client, config, native_keys))
        })
        .collect();

    let tokens = quote! {
        #![doc = " Kafka plus Kacrab runtime configuration catalog."]
        #![doc = ""]
        #![doc = " @generated by `cargo run -p kacrab-codegen -- config`."]
        #![doc = " Do not hand-edit this file; update the snapshot/policy generator instead."]

        use super::metadata::{ClientKind, ConfigEntry, ConfigOrigin, ConfigStatus};

        /// Pinned upstream Kafka config source used for this generated catalog.
        pub const KAFKA_CONFIG_SOURCE_REF: &str = #source_ref;

        #(#client_catalogs)*

        /// Kafka 4.3 plus Kacrab runtime configuration metadata.
        pub const CONFIG_CATALOG: &[ConfigEntry] = &[
            #(#catalog_entries,)*
        ];

        /// Returns the official Kafka config catalog for one client family.
        #[must_use]
        pub const fn catalog_for(client: ClientKind) -> &'static [ConfigEntry] {
            match client {
                ClientKind::Producer => PRODUCER_CONFIGS,
                ClientKind::Consumer => CONSUMER_CONFIGS,
                ClientKind::Admin => ADMIN_CONFIGS,
            }
        }
    };

    format::pretty(tokens, "Kafka config catalog")
}

/// Parse native typed config keys from `kacrab/src/config/clients.rs`.
pub fn parse_native_config_keys(source: &str) -> NativeConfigKeys {
    let mut keys = NativeConfigKeys::new();
    let mut current_client = None;
    let mut pending_key = None;

    for line in source.lines().map(str::trim) {
        if let Some(client) = parse_client_attr(line) {
            current_client = Some(client);
            pending_key = None;
            continue;
        }
        if let Some(key) = parse_string_attr(line, "key") {
            pending_key = Some(key);
            continue;
        }
        if line == "#[status(native)]"
            && let (Some(client), Some(key)) = (current_client, pending_key.take())
        {
            let _inserted = keys.insert((client, key));
        }
    }

    keys
}

fn client_catalog_tokens(
    client: &super::model::ConfigClientDocument,
    native_keys: &NativeConfigKeys,
) -> TokenStream {
    let doc = format!(
        " Kafka 4.3 {} configuration metadata plus Kacrab runtime overlays.",
        client.client.rust_doc_name()
    );
    let const_ident = client.client.const_ident();
    let entries: Vec<TokenStream> = client
        .configs
        .iter()
        .map(|config| entry_tokens(client.client, config, native_keys))
        .collect();

    quote! {
        #[doc = #doc]
        pub const #const_ident: &[ConfigEntry] = &[
            #(#entries,)*
        ];
    }
}

fn entry_tokens(
    client: KafkaConfigClient,
    config: &ConfigKeyDocument,
    native_keys: &NativeConfigKeys,
) -> TokenStream {
    let status = classify_status(client, config, native_keys);
    let origin_ident = config.origin.variant_ident();
    let client_ident = client.variant_ident();
    let key = config.key.as_str();
    let rust_field = config
        .rust_field
        .clone()
        .unwrap_or_else(|| rust_field_name(&config.key));
    let kafka_type = config.java_type.as_kafka_type();
    let default = default_string(config.default.as_ref());
    let status_expr = status.expr;
    let comment = comment_with_platforms(status.comment, &config.platforms);
    let documentation = config.documentation.as_deref().unwrap_or("");
    let source = source_url(client, config);
    let platforms = config.platforms.iter().map(String::as_str);
    let feature = option_str_tokens(config.feature.as_deref());

    quote! {
        ConfigEntry {
            client: ClientKind::#client_ident,
            origin: ConfigOrigin::#origin_ident,
            key: #key,
            rust_field: #rust_field,
            kafka_type: #kafka_type,
            default: #default,
            status: #status_expr,
            comment: #comment,
            documentation: #documentation,
            source: #source,
            platforms: &[#(#platforms),*],
            feature: #feature,
        }
    }
}

fn classify_status<'a>(
    client: KafkaConfigClient,
    config: &ConfigKeyDocument,
    native_keys: &NativeConfigKeys,
) -> StatusDecision<'a> {
    if config.origin == ConfigOrigin::KacrabRuntime {
        // Only genuine socket options carry the `socket2` feature; in-process
        // buffer/queue sizing overlays do not, so avoid labeling them "socket".
        let comment = if config.feature.as_deref() == Some("socket2") {
            "Kacrab runtime socket option generated from the runtime config overlay."
        } else {
            "Kacrab runtime option generated from the runtime config overlay."
        };
        return StatusDecision {
            expr: quote!(ConfigStatus::Native),
            comment,
        };
    }
    if native_keys.contains(&(client, config.key.clone())) {
        return StatusDecision {
            expr: quote!(ConfigStatus::Native),
            comment: "Map to a typed Rust field and support Java-style property parsing.",
        };
    }
    if config.key.starts_with("ssl.") {
        return StatusDecision {
            expr: quote!(ConfigStatus::FeatureGated {
                feature: "tls-rustls"
            }),
            comment: "TLS key can be modeled in Rust when the TLS feature is enabled; Java store \
                      formats may need conversion/skip during design-spec.",
        };
    }
    if config.key.starts_with("sasl.") {
        return StatusDecision {
            expr: quote!(ConfigStatus::FeatureGated { feature: "sasl" }),
            comment: "SASL key can be modeled in Rust when SASL support is implemented.",
        };
    }
    if is_java_only(config) {
        return StatusDecision {
            expr: quote!(ConfigStatus::SkipJavaOnly),
            comment: "Java/JVM class or plugin hook; Rust should expose typed traits/builders \
                      instead of accepting JVM class names.",
        };
    }

    StatusDecision {
        expr: quote!(ConfigStatus::NativeReview),
        comment: "Official Kafka client key; include in catalog and review exact Rust \
                  type/default before exposing it as stable typed API.",
    }
}

fn is_java_only(config: &ConfigKeyDocument) -> bool {
    matches!(config.java_type, JavaConfigType::Class)
        || matches!(config.key.rsplit('.').next(), Some("class" | "classes"))
        || config.key.contains("serializer")
        || config.key.contains("deserializer")
        || matches!(
            config.key.as_str(),
            "metric.reporters" | "config.providers" | "security.providers"
        )
}

fn default_string(default: Option<&ConfigValueDefault>) -> String {
    match default {
        None => "(none)".to_owned(),
        Some(ConfigValueDefault::Null) => "null".to_owned(),
        Some(ConfigValueDefault::Boolean(value)) => value.to_string(),
        Some(ConfigValueDefault::Integer(value)) => value.to_string(),
        Some(ConfigValueDefault::Symbol(value)) if symbol_is_no_default(value) => {
            "(none)".to_owned()
        },
        Some(ConfigValueDefault::String(value) | ConfigValueDefault::Symbol(value)) => {
            value.clone()
        },
    }
}

fn symbol_is_no_default(symbol: &str) -> bool {
    matches!(symbol, "NO_DEFAULT_VALUE" | "ConfigDef.NO_DEFAULT_VALUE")
}

fn source_url(client: KafkaConfigClient, config: &ConfigKeyDocument) -> String {
    match config.origin {
        ConfigOrigin::Kafka => format!(
            "https://kafka.apache.org/43/configuration/{}-configs/#{}configs_{}",
            client.docs_slug(),
            client.docs_anchor_prefix(),
            config.key
        ),
        ConfigOrigin::KacrabRuntime => format!("kacrab-runtime://config/{}", config.key),
    }
}

fn rust_field_name(key: &str) -> String {
    key.chars()
        .map(|ch| {
            if ch.is_ascii_alphanumeric() {
                ch.to_ascii_lowercase()
            } else {
                '_'
            }
        })
        .collect()
}

fn parse_client_attr(line: &str) -> Option<KafkaConfigClient> {
    match line {
        "#[client(Producer)]" => Some(KafkaConfigClient::Producer),
        "#[client(Consumer)]" => Some(KafkaConfigClient::Consumer),
        "#[client(Admin)]" => Some(KafkaConfigClient::Admin),
        _ => None,
    }
}

fn parse_string_attr(line: &str, attr_name: &str) -> Option<String> {
    let prefix = format!("#[{attr_name}(\"");
    let suffix = "\")]";
    line.strip_prefix(&prefix)
        .and_then(|rest| rest.strip_suffix(suffix))
        .map(str::to_owned)
}

struct StatusDecision<'a> {
    expr: TokenStream,
    comment: &'a str,
}

fn comment_with_platforms(comment: &str, platforms: &[String]) -> String {
    if platforms.is_empty() {
        return comment.to_owned();
    }
    format!("{comment} Available on {}.", platforms.join(", "))
}

fn option_str_tokens(value: Option<&str>) -> TokenStream {
    value.map_or_else(|| quote!(None), |value| quote!(Some(#value)))
}

trait KafkaConfigClientExt {
    fn const_prefix(self) -> &'static str;
    fn const_ident(self) -> Ident;
    fn docs_anchor_prefix(self) -> &'static str;
    fn docs_slug(self) -> &'static str;
    fn rust_doc_name(self) -> &'static str;
    fn variant_ident(self) -> Ident;
}

impl KafkaConfigClientExt for KafkaConfigClient {
    fn const_prefix(self) -> &'static str {
        match self {
            Self::Producer => "PRODUCER",
            Self::Consumer => "CONSUMER",
            Self::Admin => "ADMIN",
        }
    }

    fn const_ident(self) -> Ident {
        format_ident!("{}_CONFIGS", self.const_prefix())
    }

    fn docs_anchor_prefix(self) -> &'static str {
        match self {
            Self::Producer => "producer",
            Self::Consumer => "consumer",
            Self::Admin => "adminclient",
        }
    }

    fn docs_slug(self) -> &'static str {
        match self {
            Self::Producer => "producer",
            Self::Consumer => "consumer",
            Self::Admin => "admin",
        }
    }

    fn rust_doc_name(self) -> &'static str {
        match self {
            Self::Producer => "producer",
            Self::Consumer => "consumer",
            Self::Admin => "admin",
        }
    }

    fn variant_ident(self) -> Ident {
        let variant = match self {
            Self::Producer => "Producer",
            Self::Consumer => "Consumer",
            Self::Admin => "Admin",
        };
        format_ident!("{variant}")
    }
}

trait ConfigOriginExt {
    fn variant_ident(self) -> Ident;
}

impl ConfigOriginExt for ConfigOrigin {
    fn variant_ident(self) -> Ident {
        let variant = match self {
            Self::Kafka => "Kafka",
            Self::KacrabRuntime => "KacrabRuntime",
        };
        format_ident!("{variant}")
    }
}

trait JavaConfigTypeExt {
    fn as_kafka_type(&self) -> &'static str;
}

impl JavaConfigTypeExt for JavaConfigType {
    fn as_kafka_type(&self) -> &'static str {
        match self {
            Self::Boolean => "boolean",
            Self::Short => "short",
            Self::Int => "int",
            Self::Long => "long",
            Self::Double => "double",
            Self::String => "string",
            Self::List => "list",
            Self::Class => "class",
            Self::Password => "password",
        }
    }
}

#[cfg(test)]
mod tests {
    use super::{NativeConfigKeys, generate_rust_catalog, parse_native_config_keys};
    use crate::kafka_config::{
        ConfigCatalogDocument, ConfigClientDocument, ConfigKeyDocument, ConfigOrigin,
        ConfigValueDefault, JavaConfigType, KafkaConfigClient, RuntimeConfigOverlayDocument,
        merge_runtime_overlay,
    };

    #[test]
    fn parses_native_keys_from_public_client_schema() {
        let source = r#"
            kafka_config! {
                #[client(Producer)]
                pub ProducerConfig {
                    #[key("bootstrap.servers")]
                    #[status(native)]
                    bootstrap_servers: ConfigList,

                    #[key("key.serializer")]
                    #[status(skip_java_only)]
                    key_serializer: String,
                }
            }
        "#;

        let keys = parse_native_config_keys(source);

        assert!(
            keys.contains(&(KafkaConfigClient::Producer, "bootstrap.servers".to_owned())),
            "native schema parser should collect typed native keys"
        );
        assert!(
            !keys.contains(&(KafkaConfigClient::Producer, "key.serializer".to_owned())),
            "native schema parser should ignore non-native keys"
        );
    }

    #[test]
    fn generated_catalog_keeps_docs_links_and_status_policy() {
        let document = ConfigCatalogDocument {
            source_ref: "apache/kafka@4.3.0".to_owned(),
            clients: vec![ConfigClientDocument {
                client: KafkaConfigClient::Producer,
                java_class: "ProducerConfig".to_owned(),
                configs: vec![
                    ConfigKeyDocument {
                        origin: ConfigOrigin::Kafka,
                        key: "bootstrap.servers".to_owned(),
                        java_constant: "BOOTSTRAP_SERVERS_CONFIG".to_owned(),
                        rust_field: None,
                        java_type: JavaConfigType::List,
                        default: Some(ConfigValueDefault::Symbol("NO_DEFAULT_VALUE".to_owned())),
                        importance: Some("HIGH".to_owned()),
                        documentation: Some("Initial broker list.".to_owned()),
                        platforms: Vec::new(),
                        feature: None,
                    },
                    ConfigKeyDocument {
                        origin: ConfigOrigin::Kafka,
                        key: "ssl.protocol".to_owned(),
                        java_constant: "SslConfigs.SSL_PROTOCOL_CONFIG".to_owned(),
                        rust_field: None,
                        java_type: JavaConfigType::String,
                        default: Some(ConfigValueDefault::String("TLSv1.3".to_owned())),
                        importance: Some("MEDIUM".to_owned()),
                        documentation: Some("TLS protocol.".to_owned()),
                        platforms: Vec::new(),
                        feature: None,
                    },
                ],
            }],
        };
        let mut native_keys = NativeConfigKeys::new();
        assert!(
            native_keys.insert((KafkaConfigClient::Producer, "bootstrap.servers".to_owned())),
            "fixture native key should be unique"
        );

        let generated = generate_rust_catalog(&document, &native_keys)
            .expect("fixture catalog should generate valid Rust");

        assert!(
            generated.contains("pub const KAFKA_CONFIG_SOURCE_REF: &str = \"apache/kafka@4.3.0\";"),
            "generated catalog should carry the pinned source ref"
        );
        assert!(
            generated.contains("\"Initial broker list.\""),
            "generated catalog should keep official Kafka documentation"
        );
        assert!(
            generated.contains("ConfigStatus::Native"),
            "typed schema keys should be classified as native"
        );
        assert!(
            generated.contains("ConfigStatus::FeatureGated"),
            "SSL keys should remain feature gated"
        );
        assert!(
            generated.contains("feature: \"tls-rustls\""),
            "SSL keys should remain feature gated"
        );
        assert!(
            generated.contains("https://kafka.apache.org/43/configuration/producer-configs/#producerconfigs_ssl.protocol"),
            "generated catalog should link official Kafka docs"
        );
        assert!(
            syn::parse_file(&generated).is_ok(),
            "generated catalog should be valid Rust after quote lowering"
        );
    }

    #[test]
    fn runtime_overlay_expands_platform_metadata_for_each_client() {
        let document = ConfigCatalogDocument {
            source_ref: "apache/kafka@4.3.0".to_owned(),
            clients: vec![
                ConfigClientDocument {
                    client: KafkaConfigClient::Producer,
                    java_class: "ProducerConfig".to_owned(),
                    configs: Vec::new(),
                },
                ConfigClientDocument {
                    client: KafkaConfigClient::Consumer,
                    java_class: "ConsumerConfig".to_owned(),
                    configs: Vec::new(),
                },
                ConfigClientDocument {
                    client: KafkaConfigClient::Admin,
                    java_class: "AdminClientConfig".to_owned(),
                    configs: Vec::new(),
                },
            ],
        };
        let overlay: RuntimeConfigOverlayDocument = serde_json::from_str(
            r#"
            {
              "source_ref": "kacrab-runtime@0.0.1",
              "configs": [
                {
                  "key": "socket.tcp.quickack",
                  "rust_field": "socket_tcp_quickack",
                  "type": "boolean",
                  "default": null,
                  "clients": ["producer", "consumer", "admin"],
                  "platforms": ["linux", "android", "fuchsia", "cygwin"],
                  "feature": "socket2",
                  "documentation": "Sets TCP_QUICKACK after a broker connection is established."
                }
              ]
            }
            "#,
        )
        .expect("overlay fixture should parse");

        let merged = merge_runtime_overlay(document, &overlay).expect("overlay should merge");

        for client in [
            KafkaConfigClient::Producer,
            KafkaConfigClient::Consumer,
            KafkaConfigClient::Admin,
        ] {
            let config = merged
                .clients
                .iter()
                .find(|entry| entry.client == client)
                .and_then(|entry| {
                    entry
                        .configs
                        .iter()
                        .find(|config| config.key == "socket.tcp.quickack")
                })
                .expect("runtime socket key should be expanded to every selected client");

            assert_eq!(config.origin, ConfigOrigin::KacrabRuntime);
            assert_eq!(config.platforms, ["linux", "android", "fuchsia", "cygwin"]);
            assert_eq!(config.feature.as_deref(), Some("socket2"));
        }

        let generated = generate_rust_catalog(&merged, &NativeConfigKeys::new())
            .expect("merged catalog should generate");
        assert!(
            generated.contains("origin: ConfigOrigin::KacrabRuntime"),
            "runtime overlay entries should keep their origin in generated metadata"
        );
        assert!(
            generated.contains("platforms: &[\"linux\", \"android\", \"fuchsia\", \"cygwin\"]"),
            "platform metadata should be generated for socket2 runtime options"
        );
        assert!(
            generated.contains("Available on linux, android, fuchsia, cygwin."),
            "generated comments should include platform support"
        );
    }
}
